const { chromium } = require(process.env.NFTCM_PLAYWRIGHT || 'playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs');const path=require('node:path');
(async()=>{
const browser=await chromium.launch({channel:process.platform==='win32'?'msedge':undefined,headless:true});
try{
const page=await browser.newPage({viewport:{width:1500,height:1100},reducedMotion:'reduce'});const errors=[];page.on('pageerror',e=>errors.push(e.message));
const url=process.env.NFTCM_TEST_URL||'http://127.0.0.1:5173';
await page.goto(url);await page.getByRole('heading',{name:'Visão geral de compras'}).waitFor();
await page.getByText('R$ 248.500,00',{exact:true}).first().waitFor();
const out=process.env.NFTCM_QA_DIR||path.join(process.cwd(),'artifacts');fs.mkdirSync(out,{recursive:true});
await page.screenshot({path:path.join(out,'dashboard-desktop.png'),fullPage:true});
await page.getByRole('button',{name:'Análises',exact:true}).click();
await page.getByText('+11,76%',{exact:true}).waitFor();
await page.getByRole('combobox').filter({has:page.locator('option[value="6"]')}).selectOption('6');
assert.ok((await page.locator('.comparison').innerText()).includes('Sem base'));
await page.getByRole('button',{name:'Fornecedores',exact:true}).click();assert.equal(await page.locator('.supplier-card').count(),4);
await page.getByRole('button',{name:'Acessar minha base'}).click();
await page.getByRole('button',{name:'Configurações',exact:true}).first().click();
await page.getByLabel('CNPJ da unidade').fill('00000000000100');
await page.getByLabel('E-mail principal').fill('notas@example.com');
await page.getByRole('button',{name:'Salvar configurações'}).click();
await page.getByRole('status').filter({hasText:'Configurações'}).waitFor();
let base='4126061234567800019055001000000001100000000',sum=0;
for(let i=42,w=2;i>=0;i--,w=w===9?2:w+1)sum+=Number(base[i])*w;
const dv=11-sum%11,key=base+(dv>=10?0:dv);
const xml='<nfeProc xmlns="http://www.portalfiscal.inf.br/nfe"><NFe><infNFe Id="NFe'+key+'"><ide><mod>55</mod><nNF>1</nNF><dhEmi>2026-06-10T12:00:00-03:00</dhEmi><idDest>1</idDest><finNFe>1</finNFe><natOp>Venda de mercadorias</natOp></ide><emit><CNPJ>12345678000190</CNPJ><xNome>Fornecedor de teste</xNome><enderEmit><UF>PR</UF></enderEmit></emit><dest><CNPJ>00000000000100</CNPJ><enderDest><UF>PR</UF></enderDest></dest><det nItem="1"><prod><cProd>ACO</cProd><xProd>Aço teste</xProd><uCom>KG</uCom><qCom>100</qCom><vProd>1000</vProd><vDesc>50</vDesc><CFOP>5102</CFOP></prod></det><total><ICMSTot><vNF>950</vNF></ICMSTot></total></infNFe></NFe><protNFe><infProt><cStat>100</cStat><chNFe>'+key+'</chNFe></infProt></protNFe></nfeProc>';
await page.getByRole('button',{name:'Importar XML',exact:true}).click();
await page.getByLabel('Origem do documento').selectOption('Francislei');
const file={name:'nfe-teste.xml',mimeType:'text/xml',buffer:Buffer.from(xml)};
await page.getByLabel('Selecionar arquivos XML').setInputFiles(file);
await page.getByText('nfe-teste.xml: importada para revisão.').waitFor();
await page.getByLabel('Origem do documento').selectOption('Carlos');
await page.getByLabel('Selecionar arquivos XML').setInputFiles(file);
await page.getByText('nfe-teste.xml: duplicata; origem registrada.').waitFor();
await page.getByRole('button',{name:'Fechar',exact:true}).click();
assert.equal(await page.locator('tbody tr').count(),1);
assert.ok((await page.locator('tbody').innerText()).includes('Francislei, Carlos'));
await page.getByRole('button',{name:'Abrir nota 1',exact:true}).click();
await page.getByLabel('Motivo / observação').fill('Compra conferida para teste.');
await page.getByRole('checkbox').check();
await page.getByRole('button',{name:'Aprovar compra'}).click();
await page.getByRole('status').filter({hasText:'Aprovada'}).waitFor();
await page.getByRole('button',{name:'Fechar',exact:true}).click();
await page.getByRole('button',{name:'Produtos',exact:true}).click();
await page.getByRole('button',{name:'Novo produto'}).click();
await page.getByLabel('Descrição padronizada').fill('Aço padronizado');
await page.getByRole('button',{name:'Cadastrar produto',exact:true}).click();
await page.getByRole('button',{name:'Vincular',exact:true}).click();
await page.getByLabel('Produto do catálogo').selectOption({label:'Aço padronizado (KG)'});
await page.getByRole('button',{name:'Aprovar equivalência'}).click();
await page.getByText('R$ 9,50',{exact:true}).first().waitFor();
await page.getByRole('button',{name:'Visão geral',exact:true}).click();
await page.locator('.kpi').first().getByText('R$ 950,00',{exact:true}).waitFor();
await page.reload();await page.getByRole('button',{name:'Acessar minha base'}).click();
await page.locator('.kpi').first().getByText('R$ 950,00',{exact:true}).waitFor();
await page.getByRole('button',{name:'Notas fiscais',exact:true}).click();
await page.getByRole('button',{name:'Abrir nota 1',exact:true}).click();
await page.getByLabel('Motivo / observação').fill('Cancelamento confirmado para teste.');
await page.getByRole('button',{name:'Registrar cancelamento'}).click();
await page.getByRole('status').filter({hasText:'Cancelada'}).waitFor();
await page.getByRole('button',{name:'Fechar',exact:true}).click();
await page.getByRole('button',{name:'Visão geral',exact:true}).click();
await page.locator('.kpi').first().getByText('R$ 0,00',{exact:true}).waitFor();
await page.getByRole('button',{name:'Ver demonstração'}).click();
await page.setViewportSize({width:390,height:844}); await page.getByRole('button',{name:'Fechar aviso'}).click().catch(()=>{});
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
await page.screenshot({path:path.join(out,'dashboard-mobile.png'),fullPage:true});
await page.getByRole('button',{name:'Abrir menu'}).click();
await page.getByRole('button',{name:'Pendências',exact:false}).first().click();
await page.getByRole('heading',{name:'Fila de revisão'}).waitFor();
assert.deepEqual(errors,[]);
console.log('PASS: dashboard, filtros analíticos, fornecedores, configuração, XML, deduplicação, revisão, equivalência, persistência, cancelamento e mobile.');
}finally{await browser.close()}
})().catch(e=>{console.error(e);process.exit(1)});
